### ISSUE TITLE
Remove `set_pixel` and replace it with something else

### ISSUE THREAD

**Issue by LittleEndu** [python-discord/pixels#102]
I feel like directly setting a pixel is getting boring and having to figure out some other algorithm would be more interesting. One idea I had was to replace `set_pixel` with something like `set_pixel_channel` but with a catch. The channel set is the channel with index `(x + y) % 3`. This would pair excellent with the `swap_pixel` idea as the most optimal algorithm isn't immediately obvious.

**Comment by ChrisLovering** [comment]
I am closing this issue. We will be doing something *different* for the next event, but that will be planned in secret, as to not spoil the fun!
