### ISSUE TITLE
/swap_pixel and /copy_pixel

### ISSUE THREAD

**Issue by GDWR** [python-discord/pixels#81]
Suggestion add a `/move` endpoint

This will allow a user to move a pixel on *maybe* a shorter rate limit than `/set_pixel`

Things to consider are:
 - Max range of moving a pixel
 - dynamic rate limit based on distance moved

**Comment by vcokltfre** [comment]
Discussion on discord points towards 2 things:
- a /copy_pixel endpoint to copy a pixel from one location to another but NOT change the original location's pixel
- much higher ratelimits on /swap_pixel since it can be used destructively

If this is approved I'll reopen #83 with these changes

**Comment by ChrisLovering** [comment]
I am closing this issue. We will be doing something different for the next event, but that will be planned in secret, as to not spoil the fun!
