### ISSUE TITLE
Discuss: ratelimits on /swap_pixel

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/pixels#92]
An endpoint that is being heavily considered is /swap_pixel which would let you swap 2 pixels within a 10-pixel radius of each other. This could be used for dragging nearby pixels into an image or taking them from someone else's image. What we need to figure out is what we should use for the rate limit for this endpoint.

Current suggestions include:
- 1 per 45 seconds (highly unlikely, will explain further down*)
- 1 per 10 minutes

*Bear in mind the destructive factor of an endpoint like this for taking away from things other people have made, for this reason, it's likely preferable to have a longer ratelimit.

**Comment by Objectivitix** [comment]
> Bear in mind the destructive factor of an endpoint like this for taking away from things other people have made, for this reason, it's likely preferable to have a longer ratelimit.

Isn't the `/set_pixel` endpoint as destructive? Although I understand that `/swap_pixel` would be essentially like two `/set_pixel` requests, so I suggest a ratelimit of 1 per 2 minutes.

**Comment by Leterax** [comment]
Since swapping 2 pixels is the same as reading the canvas, and then setting 2 pixels manually, why the large rate limit?

**Comment by ChrisLovering** [comment]
I am closing this issue. We will be doing something different for the next event, but that will be planned in secret, as to not spoil the fun!
