### ISSUE TITLE
Suggest imagio and pure numpy over PIL for working with the canvas

### ISSUE THREAD

**Issue by Leterax** [python-discord/pixels#99]
Under "Useful tools and libraries" on <https://pixels.pythondiscord.com/info/read_canvas> we suggest the use of PIL/Pillow to work with the canvas.
In my opinion, we should suggest imageio + numpy over PIL. I have personally heard of a lot of people having problems with Pillow especially with the confusion between PIL and Pillow and how to install them. 
Using imageio and numpy makes everything more lightweight and easier from my experience. 

```py
import imageio
import numpy as np
import requests

img_bytes = requests.get(...).content
img = np.frombuffer(img_bytes, np.uint8).reshape((X, Y, 3))

imageio.imwrite("out.png", img)
```

Of course, this is only my opinion and there may be uses for PIL that I missed here!

**Comment by Leterax** [comment]
fyi: [imageio docs](https://imageio.readthedocs.io/en/stable/)

**Comment by Akarys42** [comment]
While I never tried imageio, I don't think suggestion numpy to someone who never worked with it is a good idea 😁

**Comment by ChrisLovering** [comment]
We could give alternatives in the docs, and explain why one is better over the other and in what circumstances.

Mostly using the docs as a tool to introduce people to different packages.

Notion gives readers the ability to show & hide different sections of the doc, so we should also ensure that we make use of that, so the docs don't seem too busy.
